OBJS = Date_Desmadryl.o testDate_Desmadryl.o
CC = g++
CFLAGS = -c 

# linken
main: $(OBJS)
	$(CC) $(OBJS) -o main

#testDate_Desmadryl.o: testData_Desmadryl.cpp Date_Desmadryl.h
	#$(CC) $(CFLAGS) testDate_Desmadryl.cpp

#Date_Desmadryl.o: Date_Desmadryl.cpp Date_Desmadryl.h
	#$(CC) $(CFLAGS) Date_Desmadryl.cpp

clean:
	rm -rf *.o main

